name: Cleanup Invalid Files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Find invalid Python files and delete them
        run: |
          echo "🔍 Scanning Python files..."

          VALID_REGEX="^[-a-zA-Z'éèáàíìóòúùäöüñçÉÈÁÀÍÌÓÒÚÙÄÖÜÑÇ]+_[-a-zA-Z'éèáàíìóòúùäöüñçÉÈÁÀÍÌÓÒÚÙÄÖÜÑÇ]+\.py$"

          INVALID_FILES=()

          while IFS= read -r file; do
            filename=$(basename "$file")
            if [[ ! "$filename" =~ $VALID_REGEX ]]; then
              echo "❌ Invalid: $file"
              INVALID_FILES+=("$file")
            else
              echo "✅ Valid: $file"
            fi
          done < <(find . -type f -name "*.py")

          # Delete invalid files
          if [ "${#INVALID_FILES[@]}" -eq 0 ]; then
            echo "✅ No invalid Python files found."
            exit 0
          fi

          echo "🗑️ Deleting ${#INVALID_FILES[@]} invalid file(s)..."
          for file in "${INVALID_FILES[@]}"; do
            rm -f "$file"
          done

      - name: Commit and push deletions
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -u
          if git diff --cached --quiet; then
            echo "🟢 No changes to commit."
          else
            git commit -m "Removed invalid Python files (auto-cleanup)"
            git push origin HEAD
            echo "✅ Deletions committed and pushed."
          fi


